services:
    levelab.doctrine.discriminator.subscriber:
        class: Levelab\Doctrine\DiscriminatorBundle\Event\DiscriminatorSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }